POST http://localhost:8444/api/sendWeibo
Content-Type: application/x-www-form-urlencoded

userId=1&content=content=印度报纸盛赞中国的高考检疫工作，并表示：我们印度的理工学院和医科、牙科学院考试能否借鉴一下中国的高考模式？ ​​​​


###
POST http://localhost:8444/api/predictWeibo
Content-Type: application/x-www-form-urlencoded

content=我在拼多多APP上买了一个手机屏幕，收到货安装屏幕发现，屏幕边角漏液，屏幕显示不清晰，然后找商家，商家说，是我的个人原因造成的，没有售后。商家都没有问我怎么安装的，就直接说是我个人原因造成的，明摆的是推卸责任，其中有诈**其他消费者的行为，以次充好，以假乱真，售卖三无产品，我让商家出示安全检验证书，合格证，qc认证，3c认证，对方一直发表情，不予理会，目前视为三无产品，没有合法的手续，然后我给拼多多客服打电话，要求进退款并赔偿，拼多多也是处理了好几天跟我说无法帮助您退款以及赔偿，然后我继续申诉，最后的结果是退货退款，运费由商家出，没有赔偿，我想要仅退款，我不想让屏幕继续流入市场，这属于严重不合格的残次品，然后我又找了12315处理了半个月，12315说拼多多会联系你为您处理，12315都不负责任，我申请了两回，同样以以此理由驳回。希望媒体能帮助我处理事情，目前的要求是:任何赔偿我也不要，就请把本金退给我，屏幕可以摔碎扔进垃圾桶，最后做无污染化处理 订单编号 : 20***25-22***02795 商家店铺名称: 和杰通讯科技 下单时间2020年5月25日。 非常感谢！

###
POST http://localhost:8444/api/reg
Content-Type: application/x-www-form-urlencoded

name=朱文建&pwd1=123&pwd2=123&birth=1594224000

###
